### ISSUE TITLE
"automatically stops computing when it's not being used"

### ISSUE THREAD

**Issue by mitar** [3stack-software/meteor-embox-value#4]
Hm, in the code "automatically stops computing when it's not being used" is claimed. But I do not really see this anywhere in the code to really hold? You still have to manually call `.stop()` on the resulting function to really stop the internal autorun, no?

**Comment by nathan-muir** [comment]
Hey @mitar, You're correct - it doesn't automatically stop.

The comment was from the meteor original source. As far as I can tell, this was only in the context of the Blaze rendering engine (& that code would call `.stop()`).

I'm keen on making a variant that does stop automatically (and is also lazily computed).

**Comment by mitar** [comment]
I made a variant which does stop automatically: https://github.com/peerlibrary/meteor-computed-field :-)

**Comment by nathan-muir** [comment]
Haha, thanks for that. I was just writing the magic sauce - 

```js
Tracker.afterFlush(function(){ 
   if (!self.dep. hasDependents()){ self.stop(); }
})
```

I see two issues with your version - 
  1. It appears yours will compute on creation though. 
  2. You recompute on every `get`
  3. It doesn't re-register with `Tracker.afterFlush`, so a single flush will clear that callback, causing it to no longer stop. (Might be offset by (2))

(1) is easily solved... just leave handle null.

(2) Could just check for `handle.invalidated` and only recompute then. (Inside a `Tracker.nonreactive`)
(3) would be solved by either re-binding to `Tracker.afterFlush` in the same callback, or registering on dependencies on calls to getter like so:

```js

getter = function(){
    Tracker.currentComputation.onInvalidate(function(){
      // when it's invalidated, Tracker will flush to recompute
      Tracker.afterFlush(function(){
        // after the flush, we need to see if we're still depended upon
        self.pauseIfUnused();
      })
    });
   getter.flush();
   return lastValue.get();
}

```

**Comment by mitar** [comment]
> It appears yours will compute on creation though (not lazy)

Yes, this is so that exceptions are thrown immediately, if there are any issues with the inside of the autorun. Also, this makes the initial value be set. If nobody registers dependency afterwards (which is a common case anyway) then autorun will be stopped anyway. But I think it is better for debugging.

How I see computed field package is that the internal computation is something which is cheap and can be run often, but the result is something which is rarely changed. Thus I do not mind running it often. Outside of the computed field is something which is expensive (like modifying DOM, rendering canvas), so you do not want to recompute everything every time some small reactivity dependencies change, so you wrap them into a computed field. This happens when computed field is created inside some other (outside) autorun.

I think you are looking at embox-value more like something caching of heavy computing operations. This is scenario which happens when you do not have an outside autorun.

I want to cover both cases. For example, in [Blaze Components](https://github.com/peerlibrary/meteor-blaze-components) you might want to use computed fields in the `onCreated` and then they will get dependencies registered very soon. Thus calling the computation immediately seems reasonable. (It throws errors at creation time, not read time.)

> You recompute on every get (It looks like _recompute is always called)

Yes, but `_recompute` really recomputes only if autorun was invalidated. See the code. No need to check for that outside by yourself, as you are doing.

> It doesn't re-register with Tracker.afterFlush, so a single [unrelated] flush will clear that callback, causing it to no longer stop. 

What do you mean it does not re-register? Register what? After each flush I stop or not stop the autorun? If it is stopped, it will be started at next getter, if it is not stopped, it will be be keep running until the next time it is rerun, when it will be checked again.

So every time autorun runs, I check if I can stop it.

I think it works?

I do not mind "autorun" being not stopped if it is not computing anything. If it is just in memory, be it there. But if it  reruns and there is no more dependencies, it will clean itself. I do not think it is necessary to clean itself after every get.
