### ISSUE TITLE
Is there any difference with isolateValue?

### ISSUE THREAD

**Issue by steph643** [3stack-software/meteor-embox-value#5]
https://github.com/awwx/meteor-isolate-value

**Comment by nathan-muir** [comment]
Yep.

When the value of a function wrapped by isolate-value changes, it just causes the parent helper to re-run. 

This means that the computation is run twice for each change, once to figure out that something changed, and once again when actually used.

An embox will store the result after each change, so it can be returned without recomputing it.

**Comment by mitar** [comment]
But if it is inside an autorun, it will still run twice. :-)

**Comment by steph643** [comment]
Thanks.
