### ISSUE TITLE
Lazy box template hook stop issue

### ISSUE THREAD

**Issue by rclai** [3stack-software/meteor-embox-value#6]
If you use a lazy box in a template, an error gets thrown when the template calls `stop()` `onDestroyed` because the `resultComputation` is no longer there.

https://github.com/3stack-software/meteor-embox-value/blob/master/lazy-box.js#L88

**Comment by nathan-muir** [comment]
@rclai Thanks for reporting this one. I should probably write some tests for these....

**Comment by rclai** [comment]
Cool thanks.
